"""Add impact records

Revision ID: 01e1c2517c9c
Revises: bc873c23c72d
Create Date: 2026-08-12 23:09:49.100938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e1c2517c9c'
down_revision: Union[str, Sequence[str], None] = 'bc873c23c72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects.postgresql import ENUM
    severity_enum = ENUM('low', 'medium', 'high', 'critical', name='severityenum', create_type=False)

    op.create_table('impact_records',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('system_mapping_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('severity', severity_enum, nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_mapping_id'], ['system_mappings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_records_org_id'), 'impact_records', ['org_id'], unique=False)
    op.create_index(op.f('ix_impact_records_system_mapping_id'), 'impact_records', ['system_mapping_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_impact_records_system_mapping_id'), table_name='impact_records')
    op.drop_index(op.f('ix_impact_records_org_id'), table_name='impact_records')
    op.drop_table('impact_records')
    # ### end Alembic commands ###
