"""Add LLMLog

Revision ID: 0643fd5dcef8
Revises: 0563bf9d618b
Create Date: 2026-08-11 23:40:04.189610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0643fd5dcef8'
down_revision: Union[str, Sequence[str], None] = '0563bf9d618b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_logs',
    sa.Column('pipeline_stage', sa.String(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_document_sections_raw_text_tsvector'), table_name='document_sections', postgresql_ops={'raw_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_foreign_key(None, 'policies', 'regulation_versions', ['regulation_version_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reports', 'regulations', ['regulation_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_requirement_embeddings_embedding'), table_name='requirement_embeddings', postgresql_ops={'embedding': 'vector_l2_ops'}, postgresql_using='hnsw')
    op.create_foreign_key(None, 'requirements', 'regulation_versions', ['regulation_version_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requirements', type_='foreignkey')
    op.create_index(op.f('ix_requirement_embeddings_embedding'), 'requirement_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_l2_ops'}, postgresql_using='hnsw')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.create_index(op.f('ix_document_sections_raw_text_tsvector'), 'document_sections', ['raw_text'], unique=False, postgresql_ops={'raw_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_table('llm_logs')
    # ### end Alembic commands ###
