"""Add Report status

Revision ID: 35123f542f8f
Revises: 2f1759bb3b67
Create Date: 2026-08-12 22:42:07.343399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35123f542f8f'
down_revision: Union[str, Sequence[str], None] = '2f1759bb3b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = sa.Enum('generating', 'completed', 'failed', name='reportstatusenum')
    status_enum.create(op.get_bind())
    op.add_column('reports', sa.Column('status', status_enum, nullable=False, server_default='generating'))
    op.alter_column('reports', 'storage_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'storage_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('reports', 'status')
    # ### end Alembic commands ###
