"""Add BackgroundJob

Revision ID: 3ae18eafe3a2
Revises: 01e1c2517c9c
Create Date: 2026-08-12 23:16:24.200964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ae18eafe3a2'
down_revision: Union[str, Sequence[str], None] = '01e1c2517c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('job_type', sa.Enum('ingestion', 'amendment', 'report', 'notification', name='jobtypeenum'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='jobstatusenum'), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('error_details', sa.String(), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_jobs_status'), 'background_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_background_jobs_task_id'), 'background_jobs', ['task_id'], unique=False)
    op.alter_column('impact_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_column('impact_records', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impact_records', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('impact_records', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_background_jobs_task_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_status'), table_name='background_jobs')
    op.drop_table('background_jobs')
    # ### end Alembic commands ###
