"""initial_schema

Revision ID: a88e60612ab4
Revises: 
Create Date: 2026-08-10 23:40:51.146673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'a88e60612ab4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plan', sa.Enum('trial', 'standard', 'enterprise', name='planenum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulation_versions',
    sa.Column('regulation_id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.String(), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('diff_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulation_versions_regulation_id'), 'regulation_versions', ['regulation_id'], unique=False)
    op.create_table('regulations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_documents',
    sa.Column('regulation_version_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.Enum('pdf', 'html', name='filetypeenum'), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_regulation_version_id'), 'source_documents', ['regulation_version_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_org_id'), 'api_keys', ['org_id'], unique=False)
    op.create_table('document_sections',
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('reference_label', sa.String(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_sections_source_document_id'), 'document_sections', ['source_document_id'], unique=False)
    op.create_index('ix_document_sections_raw_text_tsvector', 'document_sections', ['raw_text'], unique=False, postgresql_using='gin', postgresql_ops={'raw_text': 'gin_trgm_ops'})
    op.create_table('notifications',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('impact_alert', 'version_change', 'report_ready', name='notificationtypeenum'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_org_id'), 'notifications', ['org_id'], unique=False)
    op.create_table('policies',
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('regulation_version_id', sa.UUID(), nullable=False),
    sa.Column('requirement_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'deployed', name='policystatusenum'), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_org_id'), 'policies', ['org_id'], unique=False)
    op.create_index(op.f('ix_policies_regulation_version_id'), 'policies', ['regulation_version_id'], unique=False)
    op.create_table('reports',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('regulation_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.Enum('executive_summary', 'technical', 'audit_evidence', 'gap_analysis', 'checklist', name='reporttypeenum'), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_org_id'), 'reports', ['org_id'], unique=False)
    op.create_index(op.f('ix_reports_regulation_id'), 'reports', ['regulation_id'], unique=False)
    op.create_table('system_mappings',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('system_name', sa.String(), nullable=False),
    sa.Column('mapped_requirement_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_mappings_org_id'), 'system_mappings', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'compliance_officer', 'developer', 'legal_counsel', 'auditor', name='roleenum'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id')
    )
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_org_id'), 'audit_log', ['org_id'], unique=False)
    op.create_table('compliance_checks',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('input_payload_ref', sa.String(), nullable=False),
    sa.Column('result', sa.Enum('pass_', 'fail', 'partial', name='complianceresultenum'), nullable=False),
    sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_org_id'), 'compliance_checks', ['org_id'], unique=False)
    op.create_index(op.f('ix_compliance_checks_policy_id'), 'compliance_checks', ['policy_id'], unique=False)
    op.create_table('requirements',
    sa.Column('regulation_version_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('obligation', 'prohibition', 'permission', name='requirementtypeenum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severityenum'), nullable=False),
    sa.Column('evidence_required', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Numeric(), nullable=False),
    sa.Column('validation_status', sa.Enum('draft', 'pending_review', 'approved', 'enforceable', name='validationstatusenum'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirements_description_tsvector', 'requirements', ['description'], unique=False, postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index(op.f('ix_requirements_regulation_version_id'), 'requirements', ['regulation_version_id'], unique=False)
    op.create_index(op.f('ix_requirements_reviewed_by_user_id'), 'requirements', ['reviewed_by_user_id'], unique=False)
    op.create_index(op.f('ix_requirements_section_id'), 'requirements', ['section_id'], unique=False)
    op.create_index('ix_requirements_version_severity_status', 'requirements', ['regulation_version_id', 'severity', 'validation_status'], unique=False)
    op.create_table('requirement_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX ix_requirement_embeddings_embedding ON requirement_embeddings USING hnsw (embedding vector_l2_ops);")
    
    tenant_tables = [
        "organizations", "users", "policies", "compliance_checks",
        "system_mappings", "reports", "audit_log", "api_keys", "notifications"
    ]
    for table in tenant_tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
    
    op.execute("CREATE POLICY tenant_isolation_organizations ON organizations USING (id = current_setting('app.current_tenant', true)::uuid);")
    
    for table in tenant_tables[1:]:
        op.execute(f"CREATE POLICY tenant_isolation_{table} ON {table} USING (org_id = current_setting('app.current_tenant', true)::uuid);")
        
    op.create_foreign_key('fk_regulations_current_version_id', 'regulations', 'regulation_versions', ['current_version_id'], ['id'])
    op.create_foreign_key('fk_source_documents_regulation_version_id', 'source_documents', 'regulation_versions', ['regulation_version_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_regulation_versions_regulation_id', 'regulation_versions', 'regulations', ['regulation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_regulation_versions_source_document_id', 'regulation_versions', 'source_documents', ['source_document_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tenant_tables = [
        "organizations", "users", "policies", "compliance_checks",
        "system_mappings", "reports", "audit_log", "api_keys", "notifications"
    ]
    for table in tenant_tables[1:]:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_{table} ON {table};")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_organizations ON organizations;")
    for table in tenant_tables:
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")
        
    op.execute("DROP INDEX IF EXISTS ix_requirement_embeddings_embedding;")
    op.drop_table('requirement_embeddings')
    op.drop_index('ix_requirements_version_severity_status', table_name='requirements')
    op.drop_index(op.f('ix_requirements_section_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_reviewed_by_user_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_regulation_version_id'), table_name='requirements')
    op.drop_index('ix_requirements_description_tsvector', table_name='requirements', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.drop_table('requirements')
    op.drop_index(op.f('ix_compliance_checks_policy_id'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_org_id'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_index(op.f('ix_audit_log_org_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_mappings_org_id'), table_name='system_mappings')
    op.drop_table('system_mappings')
    op.drop_index(op.f('ix_reports_regulation_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_org_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_policies_regulation_version_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_org_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_notifications_org_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_document_sections_source_document_id'), table_name='document_sections')
    op.drop_index('ix_document_sections_raw_text_tsvector', table_name='document_sections', postgresql_using='gin', postgresql_ops={'raw_text': 'gin_trgm_ops'})
    op.drop_table('document_sections')
    op.drop_index(op.f('ix_api_keys_org_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_source_documents_regulation_version_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_table('regulations')
    op.drop_index(op.f('ix_regulation_versions_regulation_id'), table_name='regulation_versions')
    op.drop_table('regulation_versions')
    op.drop_table('organizations')
    op.create_foreign_key('fk_regulations_current_version_id', 'regulations', 'regulation_versions', ['current_version_id'], ['id'])
    op.create_foreign_key('fk_source_documents_regulation_version_id', 'source_documents', 'regulation_versions', ['regulation_version_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_regulation_versions_regulation_id', 'regulation_versions', 'regulations', ['regulation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_regulation_versions_source_document_id', 'regulation_versions', 'source_documents', ['source_document_id'], ['id'])
    # ### end Alembic commands ###
