"""Add polling fields to Regulation

Revision ID: e92c2c0eee4d
Revises: 3ae18eafe3a2
Create Date: 2026-08-12 23:25:35.315832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92c2c0eee4d'
down_revision: Union[str, Sequence[str], None] = '3ae18eafe3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulations', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('regulations', sa.Column('last_known_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulations', 'last_known_hash')
    op.drop_column('regulations', 'last_checked_at')
    # ### end Alembic commands ###
